name: Deploy

env: 
  BRANCH_NAME: $GITHUB_REF_NAME

on:
  push:
    branches:
      - 'production/app-one'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Env
      id: set_env
      run: |
        # Define directory mappings
        declare -A APP_NAMES
        APP_NAMES=(
          ["app-one"]="one"
          ["app-two"]="two"
        )

        # Extract APP_DIR from BRANCH_NAME
        APP_DIR=${BRANCH_NAME#*/}

        # Get APP_NAME based on APP_DIR
        APP_NAME=${APP_NAMES[$APP_DIR]}

        # Export variables to GitHub Actions environment
        echo "REGION_ID=cn-shanghai" >> $GITHUB_ENV
        echo "REGISTRY=registry.cn-shanghai.aliyuncs.com" >> $GITHUB_ENV
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "APP_DIR=${APP_DIR}" >> $GITHUB_ENV
        echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

    - name: Print ENV
      run: |
        echo "REGION_ID=${env.REGION_ID}"
        echo "BRANCH_NAME=${env.BRANCH_NAME}"
        echo "APP_DIR=${env.APP_DIR}"
        echo "APP_NAME=${env.APP_NAME}"
