name: Deploy

on:
  push:
    branches:
      - 'production/app-one'
env:
  REGION_ID: cn-shanghai
  REGISTRY: registry.cn-shanghai.aliyuncs.com

jobs:
  build:
    strategy:
      matrix:
        app: [{ dir: apps/app-one-folder, name: app-one },
        { dir: apps/app-two-folder, name: app-one }]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Env
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Print ENV
      run: |
        echo "${REGION_ID}"
        echo "fucking work"
    